version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: agentx
      POSTGRES_PASSWORD: agentx
      POSTGRES_DB: agentx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agentx"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: